a = input("영화 제목을 입력하세요. >")
b = input("티켓 가격을 입력하세요. >")
fl = open("movie.txt", "w")
fl.write("영화제목 : ")
fl.write(a)
fl.write("\n티켓 가격 : ")
fl.write(b)
fl.write("원")
fl2 = open("movie.txt", "r")
title = fl2.readline()